# site settings
title: Andy
subtitle: Just another dev
email: akrotchko@gmail.com
description: Andy's .
baseurl: "/home" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city:
state: MD
zip_code:
country: United States of America
phone: (240) 593-8971

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/akrotchko
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/andrew-krotchko-65a031a8/
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
